APP_PLATFORM := android-19
APP_STL	:= gnustl_static
APP_ABI := armeabi
APP_CFLAGS += -Wno-error=format-security
# APP_MODULES :=	\
#				curl			\
#				zlib			\
#				lua				\
#				json			\
#				OpenThreads		\
#				tinyxml			\
#				Jpeg2KDecode	\
#				freetype		\
#				agg				\
#				gfx				\
#				ggt				\
#				gvImage			\
#				gvModel			\
#				EnDecode		\
#				ReadMriFile		\
#				ServerClient	\
#				FDECommon		\
#				FDEGeometry		\
#				FDECore			\
#				ProviderUtil	\
#				SQLiteProvider	\
#				RenderSystem	\
#				RenderSystem_GLES	\
#				RenderDataEngine	\
#				RenderEngine		\
#				RenderControl		\